import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { HomePage } from "../components/home/home-page";
import { Footer } from "../components/footer/footer";
import { Header } from "../components/header/header";

export default function Home({ data }) {
  return (
    <div>
      <Head>
        <title>Events App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <HomePage data={data} />
      <Footer />
    </div>
  );
}

export async function getServerSideProps() {
  const { events_categories } = await import("/data/data.json");
  console.log(events_categories);
  return {
    props: {
      data: events_categories,
    },
  };
}
